### ISSUE TITLE
This package introduced breaking API changes in 0.4.x release?

### ISSUE THREAD

**Issue by Edu4rdSHL** [strayge/pylnk#14]
Hello, it is not an issue but more a question about compatibility between 0.3.0 and 0.4.x.

I have a package that depends on `pylnk>=3.0.0,<0.4.0` but the system's `pylnk` package is 0.4.2 so I want to change the dependency to simply `pylnk` for the package to avoid this problem but I wonder if there are API changes that may break the app using the latest version of `pylnk` or if it's backwards compatible.

Regards,
Ed

**Comment by strayge** [comment]
Hi,

As far I can see between 0.3.0 and 0.4.2 there is no any API changes
except `LinkInfo.remote` & `LinkInfo.local` now `0` instead of `None` [by default](https://github.com/strayge/pylnk/commit/3709fed6b89ebb4f0fce7417ac1645ac3898100c#diff-f6b6464ac56d81efbdf3e4c37fed7c660e732e0fdba913ab73972f5f785bccf7R936).

But there are significant [changes](https://github.com/strayge/pylnk/commit/d8600e280875c71a476daffcc507759212addfa4#diff-f6b6464ac56d81efbdf3e4c37fed7c660e732e0fdba913ab73972f5f785bccf7R1855) at CLI interface.

So it probably should work, but anyway you should test it.
