### ISSUE TITLE
Network location Support Missing

### ISSUE THREAD

**Issue by Matty-uk** [strayge/pylnk#4]
Hi

I was trying to output a .lnk file for network locations but could not get it to work.  I eventually came across the code comment that said this functionality was still to implement and the reference to ask for it if needed.  Any chance of adding it please?

**Comment by strayge** [comment]
@Matty-uk can you check [network_links](https://github.com/strayge/pylnk/tree/network_links) branch?

build example:
```sh
$ pylnk3.py c \\192.168.1.1\storage\Downloads\folder1\file1.txt test.lnk
```
works for me

**Comment by Matty-uk** [comment]
@strayge 

I'm receiving the below message;

> python3 pylnk3.py c \\192.168.1.1\storage\Downloads\folder1\file1.txt test.lnk
> Traceback (most recent call last):
>   File "pylnk3.py", line 1865, in <module>
>     for_file(sys.argv[2], sys.argv[3])
>   File "pylnk3.py", line 1713, in for_file
>     DriveEntry(levels[0])]
>   File "pylnk3.py", line 493, in __init__
>     raise FormatException("This is not a valid drive: " + str(drive))
> __main__.FormatException: This is not a valid drive:

**Comment by strayge** [comment]
@Matty-uk network path should start with _double_ backslash

**Comment by Matty-uk** [comment]
Sending the command as below works:
`pylnk3.py c \\\\192.168.1.1\\storage\\Downloads\\folder1\\file1.txt test.lnk`

I had been trying lnk.py (https://github.com/blacklanternsecurity/mklnk) that seems to call your code first and adds arguments, start in, comment and icon which I'm needing.

**Comment by strayge** [comment]
looks like mklnk uses old version of pylnk (for python2).

I've added similar CLI arguments to pylnk ([cli_options](https://github.com/strayge/pylnk/tree/cli_options) branch).  
```sh
usage: pylnk3.py create [-h] [--arguments [ARGUMENTS]] [--description [DESCRIPTION]]
                        [--icon [ICON]] [--icon-index [ICON_INDEX]] [--workdir [WORKDIR]]
                        [--mode [{Maximized,Normal,Minimized}]]
                        target name
```
Feel free to say if something still missing.

**Comment by Matty-uk** [comment]
Hi

I've tested and can confirm it all works.

This is great, thank you.

**Comment by strayge** [comment]
version 0.4.0 with all fixes in pypi

**Comment by int2018** [comment]
Hi,
I try to run it on a Qnap Nas Linux box as a shell script to create lnk files for the Windows clients.

Tried some variations like this but it does not work because there is no "drive":

python3 pylnk3.py c "/share/xx/liste.jpg" "/share/yy/xx.lnk"
or this: 
python3 pylnk3.py c "//192.168.1.39/share/xx/liste.jpg" "/share/yy/xx.lnk"

Output is this:
Traceback (most recent call last):
  File "pylnk3.py", line 1991, in <module>
    cli()
  File "pylnk3.py", line 1968, in cli
    for_file(
  File "pylnk3.py", line 1799, in for_file
    DriveEntry(levels[0])]
  File "pylnk3.py", line 495, in __init__
    raise FormatException("This is not a valid drive: " + str(drive))
__main__.FormatException: This is not a valid drive: /

Any idea?

**Comment by Matty-uk** [comment]
Hi int2018

Just tested with the latest version and it's still working for me, example of how I'm running it:
`python3 /u01/temp/pylnk/pylnk3.py create \\\\hostname.domain.net\\sharename\\path\\myapp.exe -a "/prm=\\\\hostname.domain.net\sharename\path\file.ncc shelld" -d "shelld" -w "%temp%" -i "\\\\hostname.domain.net\share\path\iconfile.ico" -m Normal "/u01/temp/My_New_Shortcut.lnk"`

Regards

Matt

**Comment by int2018** [comment]
ok, next step.

yes, the script on my Qnap Nas can create a lnk file. However, I cannot create a lnk with a windows-like drive letter (and path) because I get an error drive does no exist. (which is true, a drive "S:" does not exist in the linux environment). With or without quotes...
So I create a lnk like mentioned: \\192.168.1.36\path\xyz
plus a .lnk file in: /share/CACHEDEV3_DATA/path/xyz.lnk
That works

Now I open the remote location in my windows environment (Windows 10, Explorer address bar) via \\192.168.1.36\path and 
I can see files , folders and also the lnk file but the icon is gray, it is not a valid link file (for windows).
When I check the properties with right-click in the windows explorer it all looks fine. When I click OK (without having changed anything) the icon becomes a valid link (Verknüpfung) and when I click on it the target is opened.
I checked with pylnk3 -p and this action adds some information to the lnk file. 

Here is before and after:

Target file:
{ 'archive': False,
  'compressed': False,
  'directory': False,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2024-03-13 22:27:05
Modification Time: 2024-03-13 22:27:05
Access Time: 2024-03-13 22:27:05
File size: 0
Window mode: Normal
Hotkey:
File Location Info:
  (remote)
  Network Share: \\192.168.1.36\Server
  Base Name:
Description: Verknüpfung erstellt 13.03.2024 22:27:01
Used Path: \\192.168.1.36\Server\
EnvironmentVariableDataBlock
 TargetAnsi: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac\
 TargetUnicode: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac\


-----------------------------------
After clicking OK in the properties

Target file:
{ 'archive': False,
  'compressed': False,
  'directory': True,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2024-03-13 10:23:20.465912
Modification Time: 2024-03-13 10:23:20.465912
Access Time: 2024-03-13 10:23:20.799911
File size: 0
Window mode: Normal
Hotkey:
File Location Info:
  (remote)
  Network Share: \\192.168.1.36\Server
  Base Name: Anlagenabnahme\Omexom\Auriac
Description: Verknüpfung erstellt 13.03.2024 22:27:01
Relative Path: .\Anlagenabnahme\Omexom\Auriac
Used Path: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
ExtraDataBlock
 signature 0xa000000c
 data: b'<deleted>'
EnvironmentVariableDataBlock
 TargetAnsi: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
 TargetUnicode: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
ExtraDataBlock
 signature 0xa0000003
 data: b'<deletetd>'


2. scenario: I re-created the lnk again via the shell script.
When I open the remote drive via the assigned drive letter (S: in this case) in the address bar, and check the properties of the lnk file, it looks ok. But after clicking OK nothing changes, the icon remains gray and the file is not valid. In this scenario the target path with \\192 ... is not usable.

Well, maybe this is a special case but it would be nice to have an explanation :-)

**Comment by int2018** [comment]
ok, next step.

yes, the script on my Qnap Nas can create a lnk file. However, I cannot create a lnk with a windows-like drive letter (and path) because I get an error drive does no exist. (which is true, a drive "S:" does not exist in the linux environment). With or without quotes...
So I create a lnk like mentioned: \\192.168.1.36\path\xyz
plus a .lnk file in: /share/CACHEDEV3_DATA/path/xyz.lnk
That works

Now I open the remote location in my windows environment (Windows 10, Explorer address bar) via \\192.168.1.36\path and 
I can see files , folders and also the lnk file but the icon is gray, it is not a valid link file (for windows).
When I check the properties with right-click in the windows explorer it all looks fine. When I click OK (without having changed anything) the icon becomes a valid link (Verknüpfung) and when I click on it the target is opened.
I checked with pylnk3 -p and this action adds some information to the lnk file. 

Here is before and after:

Target file:
{ 'archive': False,
  'compressed': False,
  'directory': False,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2024-03-13 22:27:05
Modification Time: 2024-03-13 22:27:05
Access Time: 2024-03-13 22:27:05
File size: 0
Window mode: Normal
Hotkey:
File Location Info:
  (remote)
  Network Share: \\192.168.1.36\Server
  Base Name:
Description: Verknüpfung erstellt 13.03.2024 22:27:01
Used Path: \\192.168.1.36\Server\
EnvironmentVariableDataBlock
 TargetAnsi: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac\
 TargetUnicode: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac\


-----------------------------------
After clicking OK in the properties

Target file:
{ 'archive': False,
  'compressed': False,
  'directory': True,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2024-03-13 10:23:20.465912
Modification Time: 2024-03-13 10:23:20.465912
Access Time: 2024-03-13 10:23:20.799911
File size: 0
Window mode: Normal
Hotkey:
File Location Info:
  (remote)
  Network Share: \\192.168.1.36\Server
  Base Name: Anlagenabnahme\Omexom\Auriac
Description: Verknüpfung erstellt 13.03.2024 22:27:01
Relative Path: .\Anlagenabnahme\Omexom\Auriac
Used Path: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
ExtraDataBlock
 signature 0xa000000c
 data: b'<deleted>'
EnvironmentVariableDataBlock
 TargetAnsi: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
 TargetUnicode: \\192.168.1.36\Server\Anlagenabnahme\Omexom\Auriac
ExtraDataBlock
 signature 0xa0000003
 data: b'<deletetd>'


2. scenario: I re-created the lnk again via the shell script.
When I open the remote drive via the assigned drive letter (S: in this case) in the address bar, and check the properties of the lnk file, it looks ok. But after clicking OK nothing changes, the icon remains gray and the file is not valid. In this scenario the target path with \\192 ... is not usable.

Well, maybe this is a special case but it would be nice to have an explanation :-)


And another thing: When I have German Umlauts in the lnk filename I get an character map error:
...
  File "pylnk3.py", line 1047, in write
    write_cstring(self.base_name, lnk, padding=False)
  File "pylnk3.py", line 239, in write_cstring
    val = val.encode(DEFAULT_CHARSET)
  File ".../encodings/cp1251.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\xe4' in position 46: character maps to <undefined>

How to change the charmap
